[2025-07-18T21:39:16.383+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-18T21:39:16.465+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.validate_environment scheduled__2025-07-15T03:00:00+00:00 [queued]>
[2025-07-18T21:39:16.496+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.validate_environment scheduled__2025-07-15T03:00:00+00:00 [queued]>
[2025-07-18T21:39:16.500+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-18T21:39:16.576+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): validate_environment> on 2025-07-15 03:00:00+00:00
[2025-07-18T21:39:16.621+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'validate_environment', 'scheduled__2025-07-15T03:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmpddwqkstl']
[2025-07-18T21:39:16.616+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-18T21:39:16.624+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask validate_environment
[2025-07-18T21:39:16.634+0000] {standard_task_runner.py:72} INFO - Started process 74 to run task
[2025-07-18T21:39:16.850+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.validate_environment scheduled__2025-07-15T03:00:00+00:00 [running]> on host 9e49484b9135
[2025-07-18T21:39:17.108+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jasjot Parmar' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='validate_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T03:00:00+00:00'
[2025-07-18T21:39:17.110+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-18T21:39:17.153+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-18T21:39:17.158+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', ' \n        echo "Validating environment..."\n        test -f /app/config.yaml &&\n        test -f /app/.env &&\n        echo "Environment is valid!"\n        ']
[2025-07-18T21:39:17.220+0000] {subprocess.py:99} INFO - Output:
[2025-07-18T21:39:17.224+0000] {subprocess.py:106} INFO - Validating environment...
[2025-07-18T21:39:17.231+0000] {subprocess.py:106} INFO - Environment is valid!
[2025-07-18T21:39:17.233+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-07-18T21:39:17.321+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-18T21:39:17.323+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=validate_environment, run_id=scheduled__2025-07-15T03:00:00+00:00, execution_date=20250715T030000, start_date=20250718T213916, end_date=20250718T213917
[2025-07-18T21:39:17.467+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-18T21:39:17.558+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-18T21:39:17.567+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
