[2025-06-24T05:25:29.335+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-24T05:25:29.398+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-06-24T05:25:21.970276+00:00 [queued]>
[2025-06-24T05:25:29.422+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-06-24T05:25:21.970276+00:00 [queued]>
[2025-06-24T05:25:29.423+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-24T05:25:29.446+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-06-24 05:25:21.970276+00:00
[2025-06-24T05:25:29.483+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-24T05:25:29.493+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'manual__2025-06-24T05:25:21.970276+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmp8j999bd2']
[2025-06-24T05:25:29.498+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask execute_training
[2025-06-24T05:25:29.498+0000] {standard_task_runner.py:72} INFO - Started process 393 to run task
[2025-06-24T05:25:29.751+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training manual__2025-06-24T05:25:21.970276+00:00 [running]> on host be672ac14f72
[2025-06-24T05:25:30.025+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jasjot Parmar' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T05:25:21.970276+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T05:25:21.970276+00:00'
[2025-06-24T05:25:30.027+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-24T05:25:30.095+0000] {fraud_detection_training_dag.py:23} INFO - Initializing fraud detection training...
[2025-06-24T05:25:39.330+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-06-24T05:25:39.732+0000] {fraud_detection_training_dag.py:26} INFO - Imported FraudDetectionTraining successfully.
[2025-06-24T05:25:39.743+0000] {fraud_detection_training.py:105} INFO - Configuration loaded successfully
[2025-06-24T05:25:40.753+0000] {fraud_detection_training.py:136} INFO - Minio connection verified. Buckets: ['mlflow']
[2025-06-24T05:25:41.087+0000] {fraud_detection_training_dag.py:29} INFO - Trainer initialized successfully.
[2025-06-24T05:25:41.088+0000] {fraud_detection_training.py:484} INFO - Starting model training process...
[2025-06-24T05:25:41.088+0000] {fraud_detection_training.py:152} INFO - Connecting to Kafka Topic: transactions
[2025-06-24T05:25:41.204+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:25:41.283+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('15.223.160.19', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:41.622+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <checking_api_versions_recv> [IPv4 ('15.223.160.19', 9092)]>: Broker version identified as 2.6
[2025-06-24T05:25:41.891+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.223.160.19', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:41.892+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Connection complete.
[2025-06-24T05:25:41.893+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-06-24T05:25:41.894+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('transactions',)
[2025-06-24T05:25:42.000+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('transactions', 0), ('transactions', 1), ('transactions', 2), ('transactions', 3), ('transactions', 4), ('transactions', 5)]
[2025-06-24T05:25:42.108+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:25:42.198+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:25:42.329+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:25:42.365+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:25:42.395+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:25:42.420+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:25:42.422+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('35.182.170.137', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:42.440+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('15.157.158.196', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:42.459+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('15.223.160.19', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:42.486+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('15.157.158.196', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:42.516+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('15.223.160.19', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:42.547+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('35.182.170.137', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:25:42.859+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('35.182.170.137', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:42.860+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Connection complete.
[2025-06-24T05:25:42.861+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. 
[2025-06-24T05:25:43.040+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.157.158.196', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:43.041+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Connection complete.
[2025-06-24T05:25:43.218+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.223.160.19', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:43.219+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Connection complete.
[2025-06-24T05:25:43.392+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.157.158.196', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:43.393+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Connection complete.
[2025-06-24T05:25:43.568+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.223.160.19', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:43.569+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Connection complete.
[2025-06-24T05:25:43.816+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('35.182.170.137', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:25:43.817+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Connection complete.
[2025-06-24T05:25:43.818+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 1) to offset 0.
[2025-06-24T05:25:43.821+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 5) to offset 0.
[2025-06-24T05:25:43.822+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 3) to offset 0.
[2025-06-24T05:25:43.823+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 2) to offset 0.
[2025-06-24T05:25:43.889+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 4) to offset 0.
[2025-06-24T05:25:43.892+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 0) to offset 0.
[2025-06-24T05:27:52.806+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: socket disconnected
[2025-06-24T05:27:52.808+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.810+0000] {fetcher.py:784} ERROR - Fetch to node 7 failed: KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.812+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:52.813+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: socket disconnected
[2025-06-24T05:27:52.813+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.814+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:52.816+0000] {fetcher.py:784} ERROR - Fetch to node 1 failed: KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.817+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: socket disconnected
[2025-06-24T05:27:52.817+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.818+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:52.819+0000] {fetcher.py:784} ERROR - Fetch to node 2 failed: KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.819+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: socket disconnected
[2025-06-24T05:27:52.820+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.821+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:52.821+0000] {fetcher.py:784} ERROR - Fetch to node 3 failed: KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.822+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: socket disconnected
[2025-06-24T05:27:52.823+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.824+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:52.824+0000] {fetcher.py:784} ERROR - Fetch to node 6 failed: KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.825+0000] {conn.py:1163} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: socket disconnected
[2025-06-24T05:27:52.826+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.826+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:52.827+0000] {fetcher.py:784} ERROR - Fetch to node 5 failed: KafkaConnectionError: socket disconnected
[2025-06-24T05:27:52.867+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:52.899+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:52.931+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:52.951+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:52.975+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:52.976+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:52.977+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:52.978+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:52.978+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:52.979+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:52.980+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:52.980+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:52.980+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:52.981+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:52.981+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:52.982+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:52.982+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:52.982+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:52.983+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.022+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.042+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.065+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.066+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.066+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.067+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.068+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:53.068+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.068+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.069+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:53.069+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.069+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.070+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:53.070+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.071+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.071+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:53.084+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.085+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.085+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.086+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.086+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.087+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:53.100+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.101+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.101+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.102+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.102+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:53.103+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.103+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.104+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.104+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.105+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:53.105+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.106+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.107+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.107+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:53.130+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.131+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.132+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.132+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:53.156+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.158+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.158+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.172+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.174+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.174+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.175+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.176+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.177+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.178+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:53.201+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.203+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.203+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.204+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:53.218+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.238+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.239+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.239+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.240+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:53.256+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.257+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.258+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.259+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.260+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.261+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.262+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:53.263+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.263+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.264+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:53.281+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.283+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.284+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.285+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:53.312+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.315+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.315+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.333+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.348+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.349+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.349+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.350+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.351+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.351+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.352+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:53.352+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.353+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.353+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:53.376+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.377+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.378+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.379+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:53.391+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.393+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.394+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.394+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:53.395+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.396+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.397+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.397+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:53.420+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.422+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.423+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.424+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:53.438+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.440+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.440+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.441+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.442+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.443+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.443+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:53.457+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.460+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.460+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.461+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:53.475+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.477+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.478+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.478+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.480+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.480+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.481+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:53.505+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.516+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.519+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.524+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:53.549+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.551+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.552+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.570+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.572+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.572+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.573+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:53.587+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.589+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.589+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.589+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:53.590+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.591+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.592+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.592+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:53.593+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.594+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.595+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.595+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:53.610+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.612+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.612+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.612+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:53.662+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.664+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.665+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.683+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.700+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.701+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.702+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.703+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:53.722+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.724+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.725+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.726+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:53.727+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.728+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.729+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.731+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.732+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.732+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:53.750+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.752+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.753+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.754+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:53.780+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.782+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.783+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.784+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:53.806+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.809+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.810+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.811+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.814+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.814+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.815+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:53.837+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.839+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.840+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.841+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:53.843+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.843+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.844+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:53.862+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.864+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.865+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.865+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:53.882+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.884+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.885+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.885+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:53.901+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.903+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.904+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.905+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.907+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.907+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.908+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:53.908+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:53.911+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.911+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.912+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:53.931+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:53.933+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:53.933+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:53.934+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:54.013+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.015+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.016+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.017+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.018+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.019+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.019+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:54.034+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.035+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.036+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.037+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.038+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.039+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.039+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:54.082+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:54.084+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.084+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.085+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:54.157+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.160+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.161+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.161+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:54.227+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.229+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.229+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.230+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:54.246+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:54.248+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.248+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.249+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:54.268+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.270+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.271+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.271+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.273+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.273+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.274+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:54.341+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:54.344+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.345+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.346+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:54.489+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.491+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.491+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.492+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.494+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.494+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.494+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:54.506+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:54.507+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.508+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.508+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:54.527+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.529+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.529+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.542+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:54.555+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.556+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.556+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.557+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:54.557+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.558+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.558+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:54.559+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.559+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.560+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:54.560+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.562+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.562+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.563+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:54.606+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.607+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.608+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.609+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:54.638+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.639+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.640+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.641+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.642+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.643+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.643+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:54.850+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.852+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.852+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.853+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.855+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.855+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.856+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:54.870+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:54.872+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.873+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.873+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:54.897+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:54.899+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:54.899+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:54.900+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:55.106+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:55.108+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.108+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.109+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:55.373+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:55.375+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.376+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.377+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:55.378+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.379+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.379+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:55.467+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:55.469+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.469+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.470+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:55.573+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:55.575+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.576+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.588+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:55.590+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.590+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.591+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:55.591+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:55.593+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:55.594+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:55.594+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:56.018+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:56.020+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.020+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.021+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:56.088+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:56.090+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.090+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.091+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:56.246+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:56.248+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.249+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.249+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:56.250+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.251+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.251+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:56.293+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:56.294+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.295+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.295+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:56.296+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.297+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.297+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:56.477+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:56.478+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.479+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.479+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:27:56.490+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:56.492+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.493+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.494+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:56.495+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.495+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.496+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:56.590+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:56.592+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.593+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.593+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:56.837+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:56.838+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.839+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.839+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:27:56.947+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:56.949+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.949+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.950+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:56.951+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:56.951+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:56.952+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:27:57.178+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:57.180+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:57.180+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:57.181+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:57.182+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:57.182+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:57.183+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:27:57.366+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:57.369+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:57.369+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:57.370+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:27:58.784+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:58.786+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:58.787+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:58.787+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:27:58.971+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:58.973+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:58.973+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:58.974+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:27:59.406+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:59.409+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.409+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.410+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:27:59.411+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.412+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.412+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:27:59.458+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:59.460+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.460+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.461+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:27:59.491+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:59.507+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:59.508+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.509+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.509+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:27:59.510+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.510+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.511+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:27:59.512+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.512+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.513+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:27:59.620+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:59.622+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.622+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.623+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:59.624+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.625+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.625+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:27:59.826+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:59.828+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.829+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.829+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:27:59.830+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:27:59.831+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:27:59.831+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:28:00.080+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:00.082+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:00.082+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:00.082+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:28:00.339+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:00.342+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:00.342+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:00.342+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:28:00.862+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:00.864+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:00.865+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:00.865+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:00.867+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:00.867+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:00.868+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:28:00.986+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:00.988+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:00.988+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:00.989+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:28:04.336+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:04.338+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:04.339+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:04.340+0000] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-06-24T05:28:05.106+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:05.108+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:05.108+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:05.109+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:05.110+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:05.110+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:05.111+0000] {client_async.py:388} WARNING - Node 7 connection failed -- refreshing metadata
[2025-06-24T05:28:05.256+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:05.258+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:05.259+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:05.260+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:05.261+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:05.261+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=0 host=b0-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:05.262+0000] {client_async.py:388} WARNING - Node 0 connection failed -- refreshing metadata
[2025-06-24T05:28:05.827+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:05.829+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:05.829+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:05.830+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:05.831+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:05.831+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=11 host=b11-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:05.832+0000] {client_async.py:388} WARNING - Node 11 connection failed -- refreshing metadata
[2025-06-24T05:28:06.075+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:06.077+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.077+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.078+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:06.079+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.079+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.080+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-06-24T05:28:06.360+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:06.362+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.362+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.426+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:06.519+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:06.519+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.520+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.520+0000] {client_async.py:388} WARNING - Node 3 connection failed -- refreshing metadata
[2025-06-24T05:28:06.521+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.521+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.522+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:06.524+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.524+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.525+0000] {client_async.py:388} WARNING - Node 2 connection failed -- refreshing metadata
[2025-06-24T05:28:06.525+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:06.527+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.527+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=8 host=b8-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.527+0000] {client_async.py:388} WARNING - Node 8 connection failed -- refreshing metadata
[2025-06-24T05:28:06.612+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:06.614+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:06.614+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:06.615+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-06-24T05:28:07.090+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:07.091+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:07.092+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:07.092+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:07.094+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:07.094+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=9 host=b9-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:07.094+0000] {client_async.py:388} WARNING - Node 9 connection failed -- refreshing metadata
[2025-06-24T05:28:07.116+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:07.118+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:07.118+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:07.119+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:07.120+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:07.120+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:07.121+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-06-24T05:28:08.303+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:08.333+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-24T05:28:08.342+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=10 host=b10-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-24T05:28:08.344+0000] {client_async.py:388} WARNING - Node 10 connection failed -- refreshing metadata
[2025-06-24T05:28:15.400+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:15.914+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('35.182.170.137', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:28:15.915+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Connection complete.
[2025-06-24T05:28:18.032+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:18.492+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.157.158.196', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:28:18.493+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Connection complete.
[2025-06-24T05:28:18.517+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.157.158.196', 9092)]>: connecting to b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.157.158.196', 9092) IPv4]
[2025-06-24T05:28:19.262+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.157.158.196', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:28:19.263+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Connection complete.
[2025-06-24T05:28:19.290+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:19.744+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.223.160.19', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:28:19.745+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Connection complete.
[2025-06-24T05:28:20.344+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:28:20.805+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('35.182.170.137', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:28:20.806+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Connection complete.
[2025-06-24T05:28:20.824+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('15.223.160.19', 9092)]>: connecting to b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('15.223.160.19', 9092) IPv4]
[2025-06-24T05:28:21.289+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('15.223.160.19', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:28:21.290+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Connection complete.
[2025-06-24T05:33:16.032+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connecting> [IPv4 ('35.182.170.137', 9092)]>: connecting to b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 [('35.182.170.137', 9092) IPv4]
[2025-06-24T05:33:16.116+0000] {conn.py:497} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <handshake> [IPv4 ('35.182.170.137', 9092)]>: Loading system default SSL CAs from ('/usr/lib/ssl/cert.pem', '/usr/lib/ssl/certs', 'SSL_CERT_FILE', '/usr/lib/ssl/cert.pem', 'SSL_CERT_DIR', '/usr/lib/ssl/certs')
[2025-06-24T05:33:16.539+0000] {conn.py:822} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <authenticating> [IPv4 ('35.182.170.137', 9092)]>: Authenticated as VAWD3ORVNJTGIOBA via SASL / Plain
[2025-06-24T05:33:16.540+0000] {conn.py:467} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Connection complete.
[2025-06-24T05:36:31.721+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. 
[2025-06-24T05:36:31.722+0000] {fetcher.py:784} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.11, node_id=1 host=b1-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>
[2025-06-24T05:36:31.723+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. 
[2025-06-24T05:36:31.723+0000] {fetcher.py:784} INFO - Fetch to node 2 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.11, node_id=2 host=b2-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>
[2025-06-24T05:36:31.724+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. 
[2025-06-24T05:36:31.724+0000] {fetcher.py:784} INFO - Fetch to node 3 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.11, node_id=3 host=b3-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>
[2025-06-24T05:36:31.725+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>: Closing connection. 
[2025-06-24T05:36:31.726+0000] {fetcher.py:784} INFO - Fetch to node 5 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.11, node_id=5 host=b5-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.157.158.196', 9092)]>
[2025-06-24T05:36:31.726+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>: Closing connection. 
[2025-06-24T05:36:31.727+0000] {fetcher.py:784} INFO - Fetch to node 6 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.11, node_id=6 host=b6-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('15.223.160.19', 9092)]>
[2025-06-24T05:36:31.727+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. 
[2025-06-24T05:36:31.728+0000] {fetcher.py:784} INFO - Fetch to node 7 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.11, node_id=7 host=b7-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>
[2025-06-24T05:36:31.728+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=4 host=b4-pkc-ld537.ca-central-1.aws.confluent.cloud:9092 <connected> [IPv4 ('35.182.170.137', 9092)]>: Closing connection. 
[2025-06-24T05:36:33.122+0000] {fraud_detection_training.py:175} INFO - Total messages read from Kafka: 225722
[2025-06-24T05:36:34.634+0000] {fraud_detection_training.py:186} INFO - Kafka data read successfully with fraud rate: 3.82
[2025-06-24T05:39:36.210+0000] {fraud_detection_training.py:576} INFO - Memory usage before training (MB): 1159.75
[2025-06-24T05:39:36.210+0000] {fraud_detection_training.py:577} INFO - Starting hyperparamter tuning...
[2025-06-24T05:48:44.895+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-06-24T05:48:44.953+0000] {fraud_detection_training.py:602} INFO - Best hyperparameters: {'classifier__subsample': 0.6, 'classifier__reg_alpha': 0.5, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.05, 'classifier__gamma': 0.3, 'classifier__colsample_bytree': 0.6}
[2025-06-24T05:48:46.037+0000] {fraud_detection_training.py:616} INFO - Optimal threhsold determined: 0.8255
[2025-06-24T05:48:50.279+0000] {fraud_detection_training.py:639} INFO - Logged metrics: {'auc_pr': 0.15073243666003056, 'precision': 0.16566063044936286, 'recall': 0.1433546140452699, 'f1': 0.1537025513378967, 'threshold': 0.8255098462104797} and Best Parmaters: {'classifier__subsample': 0.6, 'classifier__reg_alpha': 0.5, 'classifier__max_depth': 5, 'classifier__learning_rate': 0.05, 'classifier__gamma': 0.3, 'classifier__colsample_bytree': 0.6} in MLFlow
[2025-06-24T05:48:50.615+0000] {fraud_detection_training.py:663} INFO - Logged Confusion Matrix: confusion_matrix_20250624_054842.png in MLFlow
[2025-06-24T05:48:51.092+0000] {fraud_detection_training.py:675} INFO - Logged Precision-Recall Curve: precision_recall_curve_20250624_054842.png in MLFlow
[2025-06-24T05:48:55.754+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

[2025-06-24T05:48:55.765+0000] {logging_mixin.py:190} WARNING - 2025/06/24 05:48:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-06-24T05:49:07.635+0000] {logging_mixin.py:190} WARNING - Registered model 'fraud_detection_model' already exists. Creating a new version of this model...
[2025-06-24T05:49:07.743+0000] {logging_mixin.py:190} WARNING - 2025/06/24 05:49:07 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: fraud_detection_model, version 18
[2025-06-24T05:49:07.744+0000] {logging_mixin.py:190} WARNING - Created version '18' of model 'fraud_detection_model'.
[2025-06-24T05:49:07.799+0000] {fraud_detection_training.py:686} INFO - Training successfully completed with metrics: {'auc_pr': 0.15073243666003056, 'precision': 0.16566063044936286, 'recall': 0.1433546140452699, 'f1': 0.1537025513378967, 'threshold': 0.8255098462104797}
[2025-06-24T05:49:07.823+0000] {logging_mixin.py:190} INFO - 🏃 View run bold-jay-830 at: http://mlflow-server:5500/#/experiments/1/runs/e9c6baddac3948a8a6cda58e2bc97549
[2025-06-24T05:49:07.824+0000] {logging_mixin.py:190} INFO - 🧪 View experiment at: http://mlflow-server:5500/#/experiments/1
[2025-06-24T05:49:08.100+0000] {python.py:240} INFO - Done. Returned value was: {'status': 'success', 'precision': {'auc_pr': 0.15073243666003056, 'precision': 0.16566063044936286, 'recall': 0.1433546140452699, 'f1': 0.1537025513378967, 'threshold': 0.8255098462104797}}
[2025-06-24T05:49:08.139+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-24T05:49:08.140+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=execute_training, run_id=manual__2025-06-24T05:25:21.970276+00:00, execution_date=20250624T052521, start_date=20250624T052529, end_date=20250624T054908
[2025-06-24T05:49:08.305+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-24T05:49:08.532+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-24T05:49:08.534+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
